# frozen_string_literal: true

desc 'buy nexmo numbers'
task buy_nexmo_numbers2: :environment do
  ary = %w[
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>
    <redacted_phone_number>

  ]

  country = 'CA'
  # country = "US"
  pattern = '1416'
  size = 100
  type = 'mobile-lvn'
  max_total = 3
  numbers_ary = []
  u = true
  u = User.find_by(email: '<redacted_email>'.downcase)
  puts u.inspect
  total = numbers_ary.length

  5.times do
    next unless total < max_total

    numbers = TextingService.search_number_nexmo(country, pattern, size, type)

    next unless u && numbers

    numbers.each_with_index do |n, _i|
      next unless ary.exclude?(n['msisdn']) && numbers_ary.exclude?(n['msisdn']) && total < max_total

      res = TextingService.buy_number_nexmo(n['country'], n['msisdn'])
      next unless res

      puts n['msisdn'].inspect
      numbers_ary.push(n['msisdn'])
      total = numbers_ary.length
      puts "number #{total} !!!!!!!!!!!!!!!"
      fn = '(' + res[1..3] + ') ' + res[4..6] + '-' + res[7..10]
      u.numbers.create(user_id: u.id, number: res, friendly_name: fn, country: n['country'], default: 0, provider: 'nexmo', price: '210')
      # TextingService.update_nexmo_number(n['country'], n['msisdn'], 'tel', '<redacted_phone_number>')
      # <redacted_phone_number>
    end
  end

  puts numbers_ary.length
end

# <redacted_phone_number>   <redacted_phone_number> TWILIO TO REMOVE

# <redacted_phone_number>
# <redacted_phone_number>
# <redacted_phone_number>
# <redacted_phone_number>
# <redacted_phone_number>
