



desc "buy nexmo numbers"
task :buy_nexmo_numbers => :environment do

  ary = [
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
    <redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>,
<redacted_phone_number>
  ]


  # toll free provisioning
  country = "US"
  pattern = "1877"
  size = 100
  type = "landline-toll-free"
  max_total = 51
  numbers_ary = []


  total = numbers_ary.length

  while (total < max_total)
    numbers = TextingService.search_number_nexmo(country, pattern, size, type)

    if numbers
      numbers.each_with_index do |n, i|
        if !(ary.include?(n["msisdn"].to_i)) && (total < max_total)
          puts n["msisdn"].inspect
          numbers_ary.push(n["msisdn"])
        end

      end
    end

    total = numbers_ary.length
  end


end


