shared: &shared
  dashboard:
    messaging:
      num_days_history: 30
      num_messages_per_user_default: 5

development: &development
  <<: *shared

test:
  <<: *development

production:
  <<: *shared