shared: &shared
  dashboard:
    messaging:
      num_days_history: 180
      num_messages_per_user_default: 300

development: &development
  <<: *shared

test:
  <<: *development

production:
  <<: *shared