drip_campaign_emails:
  cron: '0 11 * * * America/New_York' # “At 11:00 every day”
  class: "DripCampaignJob"
  args:
  description: "This job runs our drip campaigns."
  queue: drip_campaigns

weekly_activity_summary:
  cron: '0 11 * * 1 America/New_York' #“At 11am Eastern Time on Monday.”
  class: "WeeklyActivitySummaryJob"
  args:
  description: "This job send weekly activity summary."
  queue: weekly_activity_summary
  
# alert_emails:
#   #every: 15m
#   every: 15s
#   class: "MessageAlertJob"
#   args:
#   description: "This job alerts merchants of unread messages."

# card_expired_emails:
#   cron: "0 12 * * * America/New_York"
#   every: 15s
#   class: "CardExpiredJob"
#   args:
#   description: "This job notifies customers of expired or soon-to-expire cards."

recurring_campaigns: # send email for campaign list
  cron: '5 * * * *'
  class: 'RecurringCampaignJob' # class RecurringCampaignJob is present in app/jobs which represents campaign jobs
  args:
  description: 'Sends campaign to lists of users selected for campaign'
  queue: recurring_campaigns

recurring_reminders: # send email for reminder user
  cron: '5 * * * *'
  class: 'RecurringReminderJob' # class SendReminderJob is present in app/jobs which represents campaign jobs
  args:
  description: 'Sends campaign to lists of users selected for campaign'
  queue: recurring_reminders

low_account_balance_alert:
  every: 60m
  class: 'AccountBalanceAlertJob' # class SendReminderJob is present in app/jobs which represents campaign jobs
  args:
  description: 'This job alert merchant if their account balance is less than $5'
  queue: low_account_balance_alert
