#drip_campaign_emails:
#  cron: '0 11 * * * America/New_York' # “At 11:00 every day”
#  class: "DripCampaignJob"
#  args:
#  description: "This job runs our drip campaigns."
#  queue: <%= Rails.env %>_drip_campaign_emails

# Not implemented yet
#weekly_activity_summary:
#  cron: '0 11 * * 1 America/New_York' #“At 11am Eastern Time on Monday.”
#  class: "WeeklyActivitySummaryJob"
#  args:
#  description: "This job send weekly activity summary."
#  queue: <%= Rails.env %>_weekly_activity_summary

# card_expired_emails:
#   cron: "0 12 * * * America/New_York"
#   every: 15s
#   class: "CardExpiredJob"
#   args:
#   description: "This job notifies customers of expired or soon-to-expire cards."
#   queue: <%= Rails.env %>_card_expired_emails

pending_campaigns:
  cron: '*/3 * * * *'
  class: 'PendingCampaignsJob'
  args:
  description: "Checks for and queues today's upcoming campaigns"
  queue: <%= Rails.env %>_pending_campaigns

# No longer needed but will leave
#low_account_balance_alert:
#  cron: '0 12 * * * America/New_York' # “At 12:00 every day”
#  class: 'AccountBalanceAlertJob'
#  args:
#  description: 'This job alert merchant if their account balance is less than $5'
#  queue: <%= Rails.env %>_low_account_balance_alert

# Not released yet
#hosted_sms:
#  every: 15m
#  class: 'HostedSmsJob'
#  args:
#  description: 'Update response of the hosted sms service'
#  queue: <%= Rails.env %>_hosted_sms
