drip_campaign_emails:
  #cron: "0 11 * * *"    # every: 5s - Calculates time from moment of deploy...so best for frequent jobs like 10-30 mins else use cron: "30 6 * * 1"
  every: 10s
  class: "DripCampaign"
  args:
  description: "This job runs our drip campaigns."
